### ISSUE TITLE
document GitHub Actions CI

### ISSUE THREAD

**Issue by cfm** [freedomofpress/securedrop-dev-docs#181]
## Describe the change

As of freedomofpress/securedrop#7223, we have moved entirely from CircleCI to GitHub Actions.  We should take this opportunity to document the current CI workflows while they're still fresh.

## User Research Evidence

By team request.

## Additional context

- #152 
- https://wiki.freedom.press/wiki/CI,_CD_for_SecureDrop
- https://wiki.freedom.press/wiki/Demo_instance

**Comment by legoktm** [comment]
I've posted a first pass at https://github.com/freedomofpress/securedrop-dev-docs/pull/183, there's still more to do re: docs and CD. I tried to strike a balance between being useful and also not being overly specific that requires updates every time we make small change.

Regarding the internal wiki pages:
> * https://wiki.freedom.press/wiki/CI,_CD_for_SecureDrop

Nothing super useful here, will blank it and point it to the dev docs repo once my PR is merged.

> * https://wiki.freedom.press/wiki/Demo_instance

This is great, I'm going to rst-ify it and copy it basically wholesale to this repo.
