### ISSUE TITLE
Broken link causes `make docs-linkcheck` to fail

### ISSUE THREAD

**Issue by nathandyer** [freedomofpress/securedrop-dev-docs#20]
## Expected behavior

Running `make docs-linkcheck` produces no errors or warnings.

## Actual behavior

While running, it outputs:

```
securedrop-dev-docs/docs/workstation_setup.rst:78:broken link: https://docs.securedrop.org/en/stable/development/setup_development.html#qubes (404 Client Error: Not Found for url: https://docs.securedrop.org/en/stable/development/setup_development.html
```

## Steps to reproduce the problem

1. Run `make docs-linkcheck`
2. Review output to find the warning, treated as an error

**Comment by zenmonkeykstop** [comment]
https://github.com/freedomofpress/infrastructure/issues/3972 will help with this in general, but no reason not to fix the links in our own docs!
