### ISSUE TITLE
Document in more detail dbgsym packages

### ISSUE THREAD

**Issue by rocodes** [freedomofpress/securedrop-dev-docs#200]
As part of client 0.14.0 release mgmt, improve documentation around dbgsym deb packages

**Comment by legoktm** [comment]
Thanks for taking this on, happy to review.

Just to cross-link a few things that are changing / might be useful:
* https://github.com/freedomofpress/securedrop-apt-prod/issues/151
* https://github.com/freedomofpress/securedrop/pull/7347
* https://github.com/freedomofpress/securedrop-apt-test/pull/248 <-- where we learned the kernel-dbg packages were too big to upload
